baseurl = "https://blog.philippnagel.com/" # Controls base URL sitewide
languageCode = "en-US" # Controls site language
title = "Philipp Nagel" # Homepage title and page title suffix
paginate = 11 # Number of posts to show before paginating
copyright = "" # Optional, remove to suppress copyright notices

# Controls default theme and theme components
theme = [
  "fractal-forest", # OBSD
  "after-dark" # AGPL-3.0-or-later
]

disableLiveReload = false # Optional, set true to disable live reload
enableRobotsTXT = true # Suggested, enable robots.txt file

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    title = "Blog"
    url = "/index.html"
    weight = 1
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    title = "Home"
    url = "https://philippnagel.com"
    weight = 2
  [[menu.main]]
    identifier = "Search"
    name = "Search"
    title = "Search"
    url = "/search"
    weight = 3  

[markup.goldmark.renderer]
  unsafe = true # Optional, allows HTML inside your CommonMark content
[markup.tableOfContents]
  startLevel = 1 # Suggested, draws TOC using all heading levels
  endLevel = 6 # Suggested, draws TOC using all heading levels
[markup.highlight]
  noClasses = false # Suggested, used for custom syntax highlighting

[params]
  description = "" # Suggested, controls default description meta
  author = "" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  disable_csp = false # Optional, set true to disable content security policy
  images = [
    "https://source.unsplash.com/collection/983219/2000x1322"
  ] # Suggested, controls default Open Graph images

[params.layout.menu.main]
  hidden = false # Optional, set false or remove to show section menu

[params.layout.footer]
  hidden = false # Optional, set true to hide footer

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation
  
[params.hackcss]
  mode = "standard"
  palette = "light"  
